# -*- coding: utf-8 -*-
from SemanticNodes import *


# primer dl9 obraweni9 k pam9ti [member.getNouns()]
#Th. o maximalnom wablonnom pokritie
templates = [

{"SemanticNode": Greeting,
 "body": [[{"kwords":["привет", "приветствовать", "здравствовать", "здар", "здаров", "здравие", "почтение"],
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "chance": 8},

{"SemanticNode": Greeting,
 "body": [[{"kwords":["добрый", "отличный"],
            "lexems":[],
            "required": True,
            "remember": False},
           {"kwords":["вечер", "день", "утро", "денек", "утречко", "вечерок", "вечерочек"],
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "chance": 8},

{"SemanticNode": Farewell,
 "body": [[{"kwords":["досвидание", "пока", "поки", "бб"],
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "chance": 10},

# Primer: ладно, тогда выздоравливай\поправляйся; ладно давай
{"SemanticNode": Farewell,
 "body": [[{"kwords":["ладный"],
            "lexems":["ADJS"],
            "required": False,
            "remember": False}, ],
          [{"kwords":["давать","поправляться","выздоравливать"],
            "lexems":["VERB,impf,impr,excl"],
            "required": True,
            "remember": False}, ]
 ],
 "chance": 4},

{"SemanticNode": Narrative,
 "body": [[{"kwords":[],
            "lexems":["VERB,impf,indc"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Request,
 "body": [[{"kwords":["хотеть", "хотеться," "мочь", "позволить"],  # VERB,impf,1per,pres,indc
            "lexems":[],
            "required": True,
            "remember": False},
           {"kwords":["попросить", "спросить", "узнать", "уточнить"],   #Лексемы: INFN,perf,tran
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "chance": 7},

{"SemanticNode": Desire,
 "body": [[{"kwords":["хотеть", "требовать", "желать"],
            "lexems":["VERB,impf,indc"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 9},

{"SemanticNode": Recommendation,
 "body": [[{"kwords":[],
            "lexems":["VERB,impf,impr"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Confession,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,past,indc"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Planning,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,futr,indc"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Order,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,impr,excl"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Offer,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,impr,incl"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Action,
 "body": [[{"kwords":[],
            "lexems":["INFN"],
            "required": True,
            "remember": False},
            ], ],
 "chance": 8},

{"SemanticNode": Thinking,
 "body": [[{"kwords":["бы", "ли", "же"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 5},

{"SemanticNode": Yourself,
 "body": [[{"kwords":["ты"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 8},

{"SemanticNode": Myself,
 "body": [[{"kwords":["я"],  #,"себя","свой","мой", "сам", "мы"??
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 9},

{"SemanticNode": Themself,
 "body": [[{"kwords":["он","она","оно","они"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 10},

{"SemanticNode": Himself,
 "body": [[{"kwords":["сам","себя"],
            "lexems":[],
            "required": True,
            "remember": False},
            {"kwords":["сам","себя"],
            "lexems":[],
            "required": True,
            "remember": False},
          ], ],
 "chance": 7},

{"SemanticNode": FullyUsed,
 "body": [[{"kwords":["весь"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 7},

{"SemanticNode": Agression,
 "body": [[{"kwords":["слабоумный","придурковатый","тупой"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 5},

{"SemanticNode": Agression,
 "body": [[{"kwords":["даун","дебил","дурак","придурок","идиот"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 7},

{"SemanticNode": Goodwill,
 "body": [[{"kwords":["умный","искренний","надежный","приятный","дружелюбный","красивый"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 7},

{"SemanticNode": Goodwill,
 "body": [[{"kwords":["умница","молодец","победитель","красава"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 7},

{"SemanticNode": Approval,
 "body": [[{"kwords":["да","ок","согласный","одобрять","верно","правильно"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 6},

{"SemanticNode": Question,
 "body": [[{"kwords":["?"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "chance": 10},

]