# -*- coding: utf-8 -*-
from SemanticNodes import *


# primer dl9 obraweni9 k pam9ti [member.getNouns()]
#Th. o maximalnom wablonnom pokritie

#TODO Scale
templates = [

{"SemanticNode": Greeting,
 "body": [[
            {"kwords":["привет", "здаров", "почтение"],
            "lexems":[],
            "required": True,
            "remember": False},
            {"kwords":["приветствовать"],
            "lexems":["VERB,perf,sing,futr"],
            "required": True,
            "remember": False},
            {"kwords":["здравствовать"],
            "lexems":["VERB,impf,impr,excl"],
            "required": True,
            "remember": False},
           ], ],
 "type":"spec",
 "chance": 10},

{"SemanticNode": Greeting,
 "body": [[
            {"kwords":["добрый", "отличный"],
            "lexems":[],
            "required": True,
            "remember": False}],
          [
            {"kwords":["вечер", "день", "утро", "денек", "утречко", "вечерок", "вечерочек"],
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "type":"spec",
 "chance": 8},

{"SemanticNode": Farewell,
 "body": [[{"kwords":["досвидание"],
            "lexems":["NOUN,inan,gent"],
            "required": True,
            "remember": False},
            {"kwords":["пока", "поки", "бб"],
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "type":"spec",
 "chance": 10},

# Primer: ладно, тогда выздоравливай\поправляйся; ладно давай
{"SemanticNode": Farewell,
 "body": [[{"kwords":["ладный"],
            "lexems":["ADJS"],
            "required": False,
            "remember": False}],
          [{"kwords":["давать", "поправляться", "выздоравливать"],
            "lexems":["VERB,impf,impr,excl"],
            "required": True,
            "remember": False}, ]
 ],
 "type":"spec",
 "chance": 4},

{"SemanticNode": Narrative,
 "body": [[{"kwords":[],
            "lexems":["VERB,impf,indc"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 6},

{"SemanticNode": Request,
 "body": [[{"kwords":["хотеть", "хотеться"],
            "lexems":["VERB,impf,indc"],
            "required": True,
            "remember": False},
           {"kwords":["позволить"],
            "lexems":["VERB,perf,excl"],
            "required": True,
            "remember": False}],
          [
           {"kwords":["попросить", "спросить", "узнать", "уточнить"],
            "lexems":[],
            "required": True,
            "remember": False}, ], ],
 "type":"spec",
 "chance": 7},

{"SemanticNode": Desire,
 "body": [[{"kwords":["хотеть", "требовать", "желать"],
            "lexems":["VERB,impf,indc"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 9},

{"SemanticNode": Recommendation,
 "body": [[{"kwords":[],
            "lexems":["VERB,impf,impr"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 6},

{"SemanticNode": Confession,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,past,indc"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 6},

{"SemanticNode": Planning,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,futr,indc"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 6},

{"SemanticNode": Order,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,impr,excl"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 6},

{"SemanticNode": Offer,
 "body": [[{"kwords":[],
            "lexems":["VERB,perf,impr,incl"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 6},

{"SemanticNode": Action,
 "body": [[{"kwords":[],
            "lexems":["INFN"],
            "required": True,
            "remember": False},
            ], ],
 "type":"action",
 "chance": 8},

{"SemanticNode": Thinking,
 "body": [[{"kwords":["бы", "ли", "же"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"spec",
 "chance": 5},

{"SemanticNode": Yourself,
 "body": [[{"kwords":["ты"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 8},

{"SemanticNode": Yourself,
 "body": [[{"kwords":[],
            "lexems":["sing,2per"],
            "required": True,
            "remember": True},
            ], ],
 "type":"pronoun",
 "chance": 9},

{"SemanticNode": DoYou,
 "body": [[{"kwords":["вы"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 8},

{"SemanticNode": DoYou,
 "body": [[{"kwords":[],
            "lexems":["plur,2per"],
            "required": True,
            "remember": True},
            ], ],
 "type":"pronoun",
 "chance": 9},

{"SemanticNode": WeAre,
 "body": [[{"kwords":["мы"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 8},

{"SemanticNode": WeAre,
 "body": [[{"kwords":[],
            "lexems":["plur,1per"],
            "required": True,
            "remember": True},
            ], ],
 "type":"pronoun",
 "chance": 9},

{"SemanticNode": Myself,
 "body": [[{"kwords":["я"],  #,"себя","свой","мой", "сам", "мы"??
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 9},

{"SemanticNode": Myself,
 "body": [[{"kwords":[],
            "lexems":["sing,1per"],
            "required": True,
            "remember": True},
            ], ],
 "type":"pronoun",
 "chance": 9},

{"SemanticNode": Themself,
 "body": [[{"kwords":["он","она","оно"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 10},

{"SemanticNode": Themself,
 "body": [[{"kwords":[],
            "lexems":["sing,3per"],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 10},

{"SemanticNode": TheyAre,
 "body": [[{"kwords":["они"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 10},

{"SemanticNode": TheyAre,
 "body": [[{"kwords":[],
            "lexems":["plur,3per"],
            "required": True,
            "remember": False},
            ], ],
 "type":"pronoun",
 "chance": 10},

{"SemanticNode": Himself,
 "body": [[{"kwords":["сам","себя"],
            "lexems":[],
            "required": True,
            "remember": False}],
          [
            {"kwords":["сам","себя"],
            "lexems":[],
            "required": True,
            "remember": False},
          ], ],
 "type":"pronoun",
 "chance": 7},

{"SemanticNode": FullyUsed,
 "body": [[{"kwords":["весь","отовсюду"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"spec",
 "chance": 7},


{"SemanticNode": PraiseInsult,
 "body": [[{"kwords":["даун","дебил","дурак","придурок","идиот"],
            "lexems":[],
            "required": True,
            "remember": False,
            "repr":1},
            {"kwords":["слабоумный","придурковатый","тупой"],
            "lexems":[],
            "required": True,
            "remember": False,
            "repr": 2},
            {"kwords":["странный","необычный","интересный"],
            "lexems":[],
            "required": True,
            "remember": False,
            "repr":5},
            {"kwords":["хороший"],
            "lexems":[],
            "required": True,
            "remember": False,
            "repr":7},
            {"kwords":["умный","классный","прикольный","приятный"],
            "lexems":[],
            "required": True,
            "remember": False,
            "repr":8},
            {"kwords":["умница","молодец","победитель","красава"],
            "lexems":[],
            "required": True,
            "remember": False,
            "repr": 9}
            ], ],
 "type":"scale",
 "chance": 5},

{"SemanticNode": Approval,
 "body": [[{"kwords":["да","ок","верно","правильно"],
            "lexems":[],
            "required": True,
            "remember": False}],
        [
            {"kwords":["согласный","одобрять"],
            "lexems":["ADJS"],
            "required": True,
            "remember": False}
            ], ],
 "type":"spec",
 "chance": 6},

{"SemanticNode": Question,
 "body": [[{"kwords":["?"],
            "lexems":[],
            "required": True,
            "remember": False},
            ], ],
 "type":"spec",
 "chance": 10},

]